#!/bin/bash

echo '[!] Verifying if the version of masappcli has been modified'


CURRENT_VERSION=$(pip search masappcli | cut -d ' ' -f 2 | tr -d '('  | tr -d ')' | tr -d '.')
NEW_VERSION=$(cat VERSION | tr -d '.')

if [ $CURRENT_VERSION -lt $NEW_VERSION ]
then
	echo '[!] Generating new version package'
	python setup.py sdist
	echo '[!] Uploading new version to PyPI'
	twine upload dist/*
	sleep 10
	echo '[!] Verifying the upload'
	NEW_CURRENT_VERSION=$(pip search masappcli | cut -d ' ' -f 2 | tr -d '('  | tr -d ')' | tr -d '.')

	if [ $NEW_CURRENT_VERSION -ne $NEW_VERSION ]
	then
	  exit 1
  fi
fi
